// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google": {
            "post": {
                "description": "Authenticate user with Google ID token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authenticate with Google",
                "parameters": [
                    {
                        "description": "Google authentication data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GoogleAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "201": {
                        "description": "User created and logged in",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Invalid ID token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate a new JWT token from existing valid token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh JWT token",
                "responses": {
                    "200": {
                        "description": "New token generated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Invalid or missing token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Verify if the provided JWT token is valid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify JWT token",
                "responses": {
                    "200": {
                        "description": "Token is valid",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Invalid or missing token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/export/transactions": {
            "get": {
                "description": "Export transaction data with ingredient usage to Excel file. Returns Excel file with 3 sheets: Transactions (all transaction details), Ingredient Usage (ingredients used per transaction with stock changes), and Summary (statistics and top selling items). Supports date range filtering, defaults to last 30 days if dates not specified.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Export Transactions to Excel",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2024-01-01",
                        "description": "Start date in YYYY-MM-DD format. Defaults to 30 days ago if not specified.",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2024-12-31",
                        "description": "End date in YYYY-MM-DD format. Defaults to today if not specified.",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/ingredients": {
            "get": {
                "description": "Get Ingredients",
                "tags": [
                    "Ingredients"
                ],
                "summary": "Get Ingredients",
                "responses": {}
            },
            "post": {
                "description": "Post Ingredients",
                "tags": [
                    "Ingredients"
                ],
                "summary": "Post Ingredients",
                "parameters": [
                    {
                        "description": "Create ingredient",
                        "name": "ingredient",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.IngredientParamRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/ingredients/{id}": {
            "put": {
                "description": "Update an existing ingredient by ID",
                "tags": [
                    "Ingredients"
                ],
                "summary": "Update Ingredient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ingredient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated ingredient data",
                        "name": "ingredient",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.IngredientParamRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete a ingredient by ID",
                "tags": [
                    "Ingredients"
                ],
                "summary": "Delete Ingredient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ingredient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/menus": {
            "get": {
                "description": "Get all menus with ingredients",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menus"
                ],
                "summary": "Get Menus",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Create menu with image upload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menus"
                ],
                "summary": "Create Menu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Menu Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Menu Price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Menu Description",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Ingredients JSON array",
                        "name": "ingredients",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Menu Image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/menus/{id}": {
            "put": {
                "description": "Update menu by ID with optional image upload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menus"
                ],
                "summary": "Update Menu",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Menu ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Menu Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Menu Price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Menu Description",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Ingredients JSON array",
                        "name": "ingredients",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Menu Image (optional)",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete menu by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menus"
                ],
                "summary": "Delete Menu",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Menu ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "description": "Get Transactions",
                "tags": [
                    "Transactions"
                ],
                "summary": "Get Transactions",
                "responses": {}
            },
            "post": {
                "description": "Create Transaction",
                "tags": [
                    "Transactions"
                ],
                "summary": "Create Transaction",
                "parameters": [
                    {
                        "description": "Create transaction",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TransactionCreateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/transactions/{id}": {
            "get": {
                "description": "Get Transaction by ID",
                "tags": [
                    "Transactions"
                ],
                "summary": "Get Transaction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete Transaction by ID (and restore stock)",
                "tags": [
                    "Transactions"
                ],
                "summary": "Delete Transaction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/units": {
            "get": {
                "description": "Get Units",
                "tags": [
                    "Units"
                ],
                "summary": "Get Units",
                "responses": {}
            },
            "post": {
                "description": "Post Units",
                "tags": [
                    "Units"
                ],
                "summary": "Post Units",
                "parameters": [
                    {
                        "description": "Unit data",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UnitParamRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/units/{id}": {
            "put": {
                "description": "Update an existing unit by ID",
                "tags": [
                    "Units"
                ],
                "summary": "Update Unit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Unit ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated unit data",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UnitParamRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete a unit by ID",
                "tags": [
                    "Units"
                ],
                "summary": "Delete Unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unit ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/users": {
            "get": {
                "description": "Get Users",
                "tags": [
                    "Users"
                ],
                "summary": "Get Users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuthData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserData"
                }
            }
        },
        "dto.AuthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.AuthData"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.GoogleAuthRequest": {
            "type": "object",
            "required": [
                "email",
                "id_token"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id_token": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                }
            }
        },
        "dto.IngredientParamRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "stock": {
                    "type": "number"
                },
                "unit_id": {
                    "type": "integer"
                }
            }
        },
        "dto.TransactionCreateRequest": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TransactionItemRequest"
                    }
                },
                "notes": {
                    "type": "string"
                }
            }
        },
        "dto.TransactionItemRequest": {
            "type": "object",
            "required": [
                "menu_id",
                "quantity"
            ],
            "properties": {
                "menu_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "dto.UnitParamRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "dto.UserData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Awis Palace Ingredient Management API",
	Description:      "API documentation for Awis Palace Ingredient Management built with Gin and GORM.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
