// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ingredients": {
            "get": {
                "description": "Get Ingredients",
                "tags": [
                    "Ingredients"
                ],
                "summary": "Get Ingredients",
                "responses": {}
            },
            "post": {
                "description": "Post Ingredients",
                "tags": [
                    "Ingredients"
                ],
                "summary": "Post Ingredients",
                "parameters": [
                    {
                        "description": "Create ingredient",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.IngredientParamRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/units": {
            "get": {
                "description": "Get Units",
                "tags": [
                    "Units"
                ],
                "summary": "Get Units",
                "responses": {}
            },
            "post": {
                "description": "Post Units",
                "tags": [
                    "Units"
                ],
                "summary": "Post Units",
                "parameters": [
                    {
                        "description": "Unit data",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UnitParamRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/units/{id}": {
            "put": {
                "description": "Update an existing unit by ID",
                "tags": [
                    "Units"
                ],
                "summary": "Update Unit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Unit ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated unit data",
                        "name": "unit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UnitParamRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete a unit by ID",
                "tags": [
                    "Units"
                ],
                "summary": "Delete Unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unit ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/users": {
            "get": {
                "description": "Get Users",
                "tags": [
                    "Users"
                ],
                "summary": "Get Users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.IngredientParamRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "stock": {
                    "type": "number"
                },
                "unit_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UnitParamRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Awis Palace Ingredient Management API",
	Description:      "API documentation for Awis Palace Ingredient Management built with Gin and GORM.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
